// email-delivery.test.js — Unit tests for email composition and delivery
//
// Because backend/Settings.gs is a Google Apps Script file (not an ES module),
// the validation and composition logic is re-implemented here for Node.js testing.
// Tests validate email composition, subject line formatting, and parameter validation.
//
// Validates: Requirements 4.1, 4.2, 4.3, 4.5, 4.6

import { describe, it, expect } from 'vitest';

// ---------------------------------------------------------------------------
// Pure validation and composition functions extracted from sendMonthlyReportEmail
// ---------------------------------------------------------------------------

/**
 * Validate recipient email parameter
 * @param {string} recipientEmail - Email address
 * @returns {{ valid: boolean, error: string|null }}
 */
function validateRecipientEmail(recipientEmail) {
  if (!recipientEmail || typeof recipientEmail !== 'string') {
    return { valid: false, error: 'Recipient email is required and must be a string' };
  }
  
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!emailRegex.test(recipientEmail)) {
    return { valid: false, error: 'Invalid email format' };
  }
  
  return { valid: true, error: null };
}

/**
 * Validate PDF blob parameter
 * @param {any} pdfBlob - PDF blob object
 * @returns {{ valid: boolean, error: string|null }}
 */
function validatePDFBlob(pdfBlob) {
  if (!pdfBlob) {
    return { valid: false, error: 'PDF blob is required' };
  }
  return { valid: true, error: null };
}

/**
 * Validate month parameter for email
 * @param {number} month - Month number (1-12)
 * @returns {{ valid: boolean, error: string|null }}
 */
function validateEmailMonth(month) {
  if (typeof month !== 'number' || isNaN(month) || month < 1 || month > 12) {
    return { valid: false, error: 'Month must be a number between 1 and 12' };
  }
  return { valid: true, error: null };
}

/**
 * Validate year parameter for email
 * @param {number} year - Year (e.g., 2024)
 * @returns {{ valid: boolean, error: string|null }}
 */
function validateEmailYear(year) {
  if (typeof year !== 'number' || isNaN(year) || year < 2000 || year > 2100) {
    return { valid: false, error: 'Year must be a valid year between 2000 and 2100' };
  }
  return { valid: true, error: null };
}

/**
 * Compose email subject line with month and year
 * @param {number} month - Month number (1-12)
 * @param {number} year - Year (e.g., 2024)
 * @returns {string} Email subject line
 */
function composeEmailSubject(month, year) {
  const monthNames = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
  ];
  const monthName = monthNames[month - 1];
  return 'Monthly Attendance Report - ' + monthName + ' ' + year;
}

/**
 * Compose email body with explanatory message
 * @param {number} month - Month number (1-12)
 * @param {number} year - Year (e.g., 2024)
 * @param {string} orgName - Organization name
 * @returns {string} Email body text
 */
function composeEmailBody(month, year, orgName) {
  const monthNames = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
  ];
  const monthName = monthNames[month - 1];
  
  return 'Dear Administrator,\n\n' +
    'Please find attached the monthly attendance report for ' + monthName + ' ' + year + '.\n\n' +
    'This report contains a comprehensive summary of employee attendance data for the specified period, ' +
    'including on-time arrivals, late arrivals, early departures, and overall attendance statistics.\n\n' +
    'The report has been automatically generated by the ' + orgName + ' attendance management system.\n\n' +
    'If you have any questions or need additional information, please contact your system administrator.\n\n' +
    'Best regards,\n' +
    orgName + ' Attendance System';
}

/**
 * Validate all email parameters
 * @param {string} recipientEmail - Email address
 * @param {any} pdfBlob - PDF blob
 * @param {number} month - Month number (1-12)
 * @param {number} year - Year (e.g., 2024)
 * @returns {{ valid: boolean, error: string|null }}
 */
function validateEmailParameters(recipientEmail, pdfBlob, month, year) {
  const emailValidation = validateRecipientEmail(recipientEmail);
  if (!emailValidation.valid) {
    return emailValidation;
  }
  
  const blobValidation = validatePDFBlob(pdfBlob);
  if (!blobValidation.valid) {
    return blobValidation;
  }
  
  const monthValidation = validateEmailMonth(month);
  if (!monthValidation.valid) {
    return monthValidation;
  }
  
  const yearValidation = validateEmailYear(year);
  if (!yearValidation.valid) {
    return yearValidation;
  }
  
  return { valid: true, error: null };
}

// ---------------------------------------------------------------------------
// Recipient Email Validation Tests
// ---------------------------------------------------------------------------

describe('validateRecipientEmail() - valid emails', () => {
  // Validates: Requirements 4.1

  it('accepts standard email format', () => {
    const result = validateRecipientEmail('admin@company.com');
    expect(result.valid).toBe(true);
    expect(result.error).toBeNull();
  });

  it('accepts email with subdomain', () => {
    const result = validateRecipientEmail('user@mail.company.com');
    expect(result.valid).toBe(true);
  });

  it('accepts email with numbers', () => {
    const result = validateRecipientEmail('user123@example456.com');
    expect(result.valid).toBe(true);
  });

  it('accepts email with dots', () => {
    const result = validateRecipientEmail('first.last@example.com');
    expect(result.valid).toBe(true);
  });
});

describe('validateRecipientEmail() - invalid emails', () => {
  // Validates: Requirements 4.1

  it('rejects empty string', () => {
    const result = validateRecipientEmail('');
    expect(result.valid).toBe(false);
    expect(result.error).toContain('required');
  });

  it('rejects null', () => {
    const result = validateRecipientEmail(null);
    expect(result.valid).toBe(false);
  });

  it('rejects undefined', () => {
    const result = validateRecipientEmail(undefined);
    expect(result.valid).toBe(false);
  });

  it('rejects email without @ symbol', () => {
    const result = validateRecipientEmail('admincompany.com');
    expect(result.valid).toBe(false);
    expect(result.error).toContain('Invalid email format');
  });

  it('rejects email without domain', () => {
    const result = validateRecipientEmail('admin@');
    expect(result.valid).toBe(false);
  });

  it('rejects email with spaces', () => {
    const result = validateRecipientEmail('admin user@company.com');
    expect(result.valid).toBe(false);
  });

  it('rejects number', () => {
    const result = validateRecipientEmail(123);
    expect(result.valid).toBe(false);
  });

  it('rejects object', () => {
    const result = validateRecipientEmail({});
    expect(result.valid).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// PDF Blob Validation Tests
// ---------------------------------------------------------------------------

describe('validatePDFBlob() - blob validation', () => {
  // Validates: Requirements 4.2

  it('accepts non-null object as blob', () => {
    const mockBlob = { type: 'application/pdf', name: 'report.pdf' };
    const result = validatePDFBlob(mockBlob);
    expect(result.valid).toBe(true);
    expect(result.error).toBeNull();
  });

  it('accepts any truthy value as blob', () => {
    const result = validatePDFBlob('blob-data');
    expect(result.valid).toBe(true);
  });

  it('rejects null', () => {
    const result = validatePDFBlob(null);
    expect(result.valid).toBe(false);
    expect(result.error).toContain('required');
  });

  it('rejects undefined', () => {
    const result = validatePDFBlob(undefined);
    expect(result.valid).toBe(false);
  });

  it('rejects empty string', () => {
    const result = validatePDFBlob('');
    expect(result.valid).toBe(false);
  });

  it('rejects 0', () => {
    const result = validatePDFBlob(0);
    expect(result.valid).toBe(false);
  });

  it('rejects false', () => {
    const result = validatePDFBlob(false);
    expect(result.valid).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Month/Year Validation Tests for Email
// ---------------------------------------------------------------------------

describe('validateEmailMonth() - valid months', () => {
  // Validates: Requirements 4.5

  it('accepts month = 1', () => {
    const result = validateEmailMonth(1);
    expect(result.valid).toBe(true);
  });

  it('accepts month = 12', () => {
    const result = validateEmailMonth(12);
    expect(result.valid).toBe(true);
  });

  it('accepts all valid months 1-12', () => {
    for (let month = 1; month <= 12; month++) {
      const result = validateEmailMonth(month);
      expect(result.valid).toBe(true);
    }
  });
});

describe('validateEmailMonth() - invalid months', () => {
  // Validates: Requirements 4.5

  it('rejects month = 0', () => {
    const result = validateEmailMonth(0);
    expect(result.valid).toBe(false);
  });

  it('rejects month = 13', () => {
    const result = validateEmailMonth(13);
    expect(result.valid).toBe(false);
  });

  it('rejects NaN', () => {
    const result = validateEmailMonth(NaN);
    expect(result.valid).toBe(false);
  });

  it('rejects string', () => {
    const result = validateEmailMonth('6');
    expect(result.valid).toBe(false);
  });
});

describe('validateEmailYear() - valid years', () => {
  // Validates: Requirements 4.5

  it('accepts year = 2000', () => {
    const result = validateEmailYear(2000);
    expect(result.valid).toBe(true);
  });

  it('accepts year = 2100', () => {
    const result = validateEmailYear(2100);
    expect(result.valid).toBe(true);
  });

  it('accepts year = 2024', () => {
    const result = validateEmailYear(2024);
    expect(result.valid).toBe(true);
  });
});

describe('validateEmailYear() - invalid years', () => {
  // Validates: Requirements 4.5

  it('rejects year = 1999', () => {
    const result = validateEmailYear(1999);
    expect(result.valid).toBe(false);
  });

  it('rejects year = 2101', () => {
    const result = validateEmailYear(2101);
    expect(result.valid).toBe(false);
  });

  it('rejects NaN', () => {
    const result = validateEmailYear(NaN);
    expect(result.valid).toBe(false);
  });

  it('rejects string', () => {
    const result = validateEmailYear('2024');
    expect(result.valid).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Email Subject Composition Tests
// ---------------------------------------------------------------------------

describe('composeEmailSubject() - subject line formatting', () => {
  // Validates: Requirements 4.5, 4.6

  it('includes month name in subject', () => {
    const subject = composeEmailSubject(1, 2024);
    expect(subject).toContain('January');
  });

  it('includes year in subject', () => {
    const subject = composeEmailSubject(1, 2024);
    expect(subject).toContain('2024');
  });

  it('includes "Monthly Attendance Report" in subject', () => {
    const subject = composeEmailSubject(1, 2024);
    expect(subject).toContain('Monthly Attendance Report');
  });

  it('formats January 2024 correctly', () => {
    const subject = composeEmailSubject(1, 2024);
    expect(subject).toBe('Monthly Attendance Report - January 2024');
  });

  it('formats December 2024 correctly', () => {
    const subject = composeEmailSubject(12, 2024);
    expect(subject).toBe('Monthly Attendance Report - December 2024');
  });

  it('formats June 2023 correctly', () => {
    const subject = composeEmailSubject(6, 2023);
    expect(subject).toBe('Monthly Attendance Report - June 2023');
  });

  it('formats all months correctly', () => {
    const monthNames = [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'
    ];
    for (let month = 1; month <= 12; month++) {
      const subject = composeEmailSubject(month, 2024);
      expect(subject).toBe(`Monthly Attendance Report - ${monthNames[month - 1]} 2024`);
    }
  });

  it('uses consistent format with hyphen separator', () => {
    const subject = composeEmailSubject(3, 2024);
    expect(subject).toMatch(/^Monthly Attendance Report - \w+ \d{4}$/);
  });
});

// ---------------------------------------------------------------------------
// Email Body Composition Tests
// ---------------------------------------------------------------------------

describe('composeEmailBody() - body content', () => {
  // Validates: Requirements 4.6

  it('includes greeting', () => {
    const body = composeEmailBody(1, 2024, 'Test Company');
    expect(body).toContain('Dear Administrator');
  });

  it('includes month name in body', () => {
    const body = composeEmailBody(1, 2024, 'Test Company');
    expect(body).toContain('January');
  });

  it('includes year in body', () => {
    const body = composeEmailBody(1, 2024, 'Test Company');
    expect(body).toContain('2024');
  });

  it('includes organization name in body', () => {
    const body = composeEmailBody(1, 2024, 'Test Company');
    expect(body).toContain('Test Company');
  });

  it('mentions attachment', () => {
    const body = composeEmailBody(1, 2024, 'Test Company');
    expect(body).toContain('attached');
  });

  it('explains report content', () => {
    const body = composeEmailBody(1, 2024, 'Test Company');
    expect(body).toContain('attendance data');
    expect(body).toContain('on-time arrivals');
    expect(body).toContain('late arrivals');
    expect(body).toContain('early departures');
  });

  it('includes signature with organization name', () => {
    const body = composeEmailBody(1, 2024, 'Test Company');
    expect(body).toContain('Best regards');
    expect(body).toContain('Test Company Attendance System');
  });

  it('uses different organization names correctly', () => {
    const body1 = composeEmailBody(1, 2024, 'Company A');
    const body2 = composeEmailBody(1, 2024, 'Company B');
    expect(body1).toContain('Company A');
    expect(body2).toContain('Company B');
    expect(body1).not.toContain('Company B');
    expect(body2).not.toContain('Company A');
  });

  it('formats different months correctly', () => {
    const bodyJan = composeEmailBody(1, 2024, 'Test Company');
    const bodyDec = composeEmailBody(12, 2024, 'Test Company');
    expect(bodyJan).toContain('January 2024');
    expect(bodyDec).toContain('December 2024');
  });

  it('includes newlines for proper formatting', () => {
    const body = composeEmailBody(1, 2024, 'Test Company');
    expect(body).toContain('\n\n');
  });
});

// ---------------------------------------------------------------------------
// Complete Parameter Validation Tests
// ---------------------------------------------------------------------------

describe('validateEmailParameters() - complete validation', () => {
  // Validates: Requirements 4.1, 4.2, 4.5

  const mockBlob = { type: 'application/pdf' };

  it('accepts all valid parameters', () => {
    const result = validateEmailParameters('admin@company.com', mockBlob, 1, 2024);
    expect(result.valid).toBe(true);
    expect(result.error).toBeNull();
  });

  it('rejects invalid email', () => {
    const result = validateEmailParameters('invalid-email', mockBlob, 1, 2024);
    expect(result.valid).toBe(false);
    expect(result.error).toContain('email');
  });

  it('rejects null blob', () => {
    const result = validateEmailParameters('admin@company.com', null, 1, 2024);
    expect(result.valid).toBe(false);
    expect(result.error).toContain('blob');
  });

  it('rejects invalid month', () => {
    const result = validateEmailParameters('admin@company.com', mockBlob, 13, 2024);
    expect(result.valid).toBe(false);
    expect(result.error).toContain('Month');
  });

  it('rejects invalid year', () => {
    const result = validateEmailParameters('admin@company.com', mockBlob, 1, 1999);
    expect(result.valid).toBe(false);
    expect(result.error).toContain('Year');
  });

  it('validates parameters in order (email first)', () => {
    const result = validateEmailParameters('', mockBlob, 1, 2024);
    expect(result.valid).toBe(false);
    expect(result.error).toContain('email');
  });

  it('validates parameters in order (blob second)', () => {
    const result = validateEmailParameters('admin@company.com', null, 1, 2024);
    expect(result.valid).toBe(false);
    expect(result.error).toContain('blob');
  });

  it('validates parameters in order (month third)', () => {
    const result = validateEmailParameters('admin@company.com', mockBlob, 0, 2024);
    expect(result.valid).toBe(false);
    expect(result.error).toContain('Month');
  });

  it('validates parameters in order (year fourth)', () => {
    const result = validateEmailParameters('admin@company.com', mockBlob, 1, 2101);
    expect(result.valid).toBe(false);
    expect(result.error).toContain('Year');
  });
});

// ---------------------------------------------------------------------------
// Email Composition Integration Tests
// ---------------------------------------------------------------------------

describe('Email composition integration', () => {
  // Validates: Requirements 4.5, 4.6

  it('composes complete email with all required elements', () => {
    const subject = composeEmailSubject(3, 2024);
    const body = composeEmailBody(3, 2024, 'Test Organization');
    
    // Subject should include month and year
    expect(subject).toContain('March');
    expect(subject).toContain('2024');
    
    // Body should include month, year, and organization
    expect(body).toContain('March');
    expect(body).toContain('2024');
    expect(body).toContain('Test Organization');
    
    // Body should explain the attachment
    expect(body).toContain('attached');
    expect(body).toContain('report');
  });

  it('maintains consistency between subject and body', () => {
    const month = 6;
    const year = 2023;
    const subject = composeEmailSubject(month, year);
    const body = composeEmailBody(month, year, 'Company');
    
    // Both should reference the same month
    expect(subject).toContain('June');
    expect(body).toContain('June');
    
    // Both should reference the same year
    expect(subject).toContain('2023');
    expect(body).toContain('2023');
  });

  it('handles different organization names in body', () => {
    const body1 = composeEmailBody(1, 2024, 'Organization Alpha');
    const body2 = composeEmailBody(1, 2024, 'Organization Beta');
    
    expect(body1).toContain('Organization Alpha');
    expect(body2).toContain('Organization Beta');
  });

  it('creates professional email format', () => {
    const subject = composeEmailSubject(4, 2024);
    const body = composeEmailBody(4, 2024, 'Professional Corp');
    
    // Subject should be concise
    expect(subject.length).toBeLessThan(100);
    
    // Body should have greeting and signature
    expect(body).toContain('Dear');
    expect(body).toContain('Best regards');
    
    // Body should be informative
    expect(body.length).toBeGreaterThan(100);
  });
});
