// integration-email-workflow.test.js — Integration tests for the complete email workflow
//
// Verifies that all email functions are properly wired together:
//   getEmailSettings / saveEmailSettings → PropertiesService storage
//   saveEmailSettings → setupEmailScheduleTrigger / removeEmailScheduleTrigger
//   handleScheduledEmailSend → generateMonthlyReportPDF → sendMonthlyReportEmail → logEmailDelivery
//   sendManualMonthlyReport → generateMonthlyReportPDF → sendMonthlyReportEmail → logEmailDelivery
//   getEmailDeliveryLogs → Email_Delivery_Log sheet
//
// Requirements: 4.1, 4.2, 4.3, 8.1, 8.2, 8.3, 8.4, 8.5, 8.6

import { describe, it, expect } from 'vitest';

// ---------------------------------------------------------------------------
// Shared pure-logic helpers (mirrors Settings.gs without GAS dependencies)
// ---------------------------------------------------------------------------

/** Validate email format — mirrors Settings.gs regex */
function validateEmailFormat(email) {
  if (!email || typeof email !== 'string') return false;
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

/** Validate schedule parameters — mirrors setupEmailScheduleTrigger validation */
function validateSchedule(day, hour, minute) {
  if (typeof day !== 'number' || isNaN(day) || day < 1 || day > 28 || !Number.isInteger(day)) {
    return { valid: false, error: 'Day must be an integer between 1 and 28' };
  }
  if (typeof hour !== 'number' || isNaN(hour) || hour < 0 || hour > 23 || !Number.isInteger(hour)) {
    return { valid: false, error: 'Hour must be an integer between 0 and 23' };
  }
  if (typeof minute !== 'number' || isNaN(minute) || minute < 0 || minute > 59 || !Number.isInteger(minute)) {
    return { valid: false, error: 'Minute must be an integer between 0 and 59' };
  }
  return { valid: true, error: null };
}

/** Simulate PropertiesService round-trip — mirrors getEmailSettings / saveEmailSettings */
function simulateSettingsStorage(emailData) {
  // Store (mirrors saveEmailSettings)
  const stored = {
    MONTHLY_EMAIL_ENABLED:         emailData.enabled ? 'true' : 'false',
    MONTHLY_EMAIL_RECIPIENT:       emailData.recipient || '',
    MONTHLY_EMAIL_SCHEDULE_DAY:    String(emailData.scheduleDay),
    MONTHLY_EMAIL_SCHEDULE_HOUR:   String(emailData.scheduleHour),
    MONTHLY_EMAIL_SCHEDULE_MINUTE: String(emailData.scheduleMinute)
  };

  // Retrieve (mirrors getEmailSettings)
  return {
    enabled:        stored.MONTHLY_EMAIL_ENABLED === 'true',
    recipient:      stored.MONTHLY_EMAIL_RECIPIENT,
    scheduleDay:    parseInt(stored.MONTHLY_EMAIL_SCHEDULE_DAY,    10),
    scheduleHour:   parseInt(stored.MONTHLY_EMAIL_SCHEDULE_HOUR,   10),
    scheduleMinute: parseInt(stored.MONTHLY_EMAIL_SCHEDULE_MINUTE, 10)
  };
}

/** Simulate trigger lifecycle — mirrors setupEmailScheduleTrigger / removeEmailScheduleTrigger */
function simulateTriggerLifecycle(day, hour, minute) {
  const validation = validateSchedule(day, hour, minute);
  if (!validation.valid) {
    return { success: false, triggerId: null, error: validation.error };
  }
  const triggerId = 'trigger_' + day + '_' + hour + '_' + minute;
  return { success: true, triggerId, error: null };
}

/** Simulate previous-month calculation — mirrors handleScheduledEmailSend */
function calculatePreviousMonth(now) {
  let month = now.getMonth(); // 0-11
  let year  = now.getFullYear();

  if (month === 0) {
    // January → previous month is December of previous year
    month = 12;
    year  = year - 1;
  }
  // For any other month, getMonth() (0-indexed) equals the previous month in 1-indexed
  // e.g. getMonth()=3 (April) → previous month = March = 3 (1-indexed)
  const reportMonth = month;
  return {
    month:     reportMonth,
    year,
    monthYear: year + '-' + String(reportMonth).padStart(2, '0')
  };
}

/** Simulate email composition — mirrors sendMonthlyReportEmail */
function composeEmail(recipientEmail, month, year, orgName) {
  const monthNames = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
  ];
  const monthName = monthNames[month - 1];
  return {
    to:      recipientEmail,
    subject: 'Monthly Attendance Report - ' + monthName + ' ' + year,
    body:    'Dear Administrator,\n\nPlease find attached the monthly attendance report for ' +
             monthName + ' ' + year + '.\n\n' +
             'The report has been automatically generated by the ' + orgName + ' attendance management system.\n\n' +
             'Best regards,\n' + orgName + ' Attendance System'
  };
}

/** Simulate delivery log entry — mirrors logEmailDelivery */
function createLogEntry(recipient, monthYear, status, triggerType, errorMessage) {
  return {
    timestamp:    new Date().toISOString(),
    recipient,
    monthYear,
    status,
    errorMessage: errorMessage || '',
    triggerType
  };
}

/** Simulate the complete scheduled send workflow */
function simulateScheduledSend(settings, pdfSuccess, emailSuccess) {
  if (!settings.enabled) {
    return { skipped: true, reason: 'Automatic monthly emails are disabled' };
  }

  if (!settings.recipient) {
    const log = createLogEntry('unknown', '', 'failed', 'scheduled', 'No recipient email configured');
    return { success: false, log };
  }

  const now = new Date();
  const { month, year, monthYear } = calculatePreviousMonth(now);

  if (!pdfSuccess) {
    const log = createLogEntry(settings.recipient, monthYear, 'failed', 'scheduled', 'PDF generation failed');
    return { success: false, log };
  }

  if (!emailSuccess) {
    const log = createLogEntry(settings.recipient, monthYear, 'failed', 'scheduled', 'Email delivery failed');
    return { success: false, log };
  }

  const log = createLogEntry(settings.recipient, monthYear, 'success', 'scheduled', '');
  return { success: true, log, month, year, monthYear };
}

/** Simulate the complete manual send workflow */
function simulateManualSend(settings, pdfSuccess, emailSuccess) {
  if (!settings.recipient || !validateEmailFormat(settings.recipient)) {
    return {
      success: false,
      error: settings.recipient
        ? 'Invalid recipient email format. Please update email settings.'
        : 'No recipient email configured. Please configure email settings first.'
    };
  }

  const now = new Date();
  const month = now.getMonth() + 1;
  const year  = now.getFullYear();
  const monthYear = year + '-' + String(month).padStart(2, '0');

  if (!pdfSuccess) {
    const log = createLogEntry(settings.recipient, monthYear, 'failed', 'manual', 'PDF generation failed');
    return { success: false, error: 'Failed to generate PDF report', log };
  }

  if (!emailSuccess) {
    const log = createLogEntry(settings.recipient, monthYear, 'failed', 'manual', 'Email delivery failed');
    return { success: false, error: 'Failed to send email', log };
  }

  const log = createLogEntry(settings.recipient, monthYear, 'success', 'manual', '');
  return { success: true, error: null, log, recipient: settings.recipient, monthYear };
}

// ---------------------------------------------------------------------------
// 1. Configuration → Storage → Trigger wiring
// ---------------------------------------------------------------------------

describe('Configuration save wires trigger setup correctly', () => {
  // Validates: Requirements 8.1, 8.4 — saveEmailSettings calls setupEmailScheduleTrigger

  it('enabling automatic emails creates a trigger with the saved schedule', () => {
    const emailData = { enabled: true, recipient: 'admin@company.com', scheduleDay: 5, scheduleHour: 9, scheduleMinute: 0 };

    // Step 1: validate and store settings
    const retrieved = simulateSettingsStorage(emailData);
    expect(retrieved.enabled).toBe(true);
    expect(retrieved.scheduleDay).toBe(5);

    // Step 2: trigger should be created with the stored schedule
    const trigger = simulateTriggerLifecycle(retrieved.scheduleDay, retrieved.scheduleHour, retrieved.scheduleMinute);
    expect(trigger.success).toBe(true);
    expect(trigger.triggerId).toBeTruthy();
  });

  it('disabling automatic emails removes the trigger', () => {
    // Simulate: was enabled with a trigger, now disabled
    const initialData = { enabled: true, recipient: 'admin@company.com', scheduleDay: 5, scheduleHour: 9, scheduleMinute: 0 };
    const trigger = simulateTriggerLifecycle(initialData.scheduleDay, initialData.scheduleHour, initialData.scheduleMinute);
    expect(trigger.success).toBe(true);

    // Disable: trigger should be removed (simulated by null triggerId)
    const disabledData = { ...initialData, enabled: false };
    const retrieved = simulateSettingsStorage(disabledData);
    expect(retrieved.enabled).toBe(false);

    // No trigger should be created when disabled
    // (In real code, removeEmailScheduleTrigger() is called instead)
    const shouldNotCreateTrigger = !retrieved.enabled;
    expect(shouldNotCreateTrigger).toBe(true);
  });

  it('updating schedule replaces the existing trigger', () => {
    const original = simulateTriggerLifecycle(5, 9, 0);
    const updated  = simulateTriggerLifecycle(15, 14, 30);

    expect(original.success).toBe(true);
    expect(updated.success).toBe(true);
    // Different schedules produce different trigger IDs
    expect(original.triggerId).not.toBe(updated.triggerId);
  });
});

// ---------------------------------------------------------------------------
// 2. Settings persistence round-trip
// ---------------------------------------------------------------------------

describe('Email settings persist and retrieve correctly', () => {
  // Validates: Requirements 8.1, 8.2 — getEmailSettings returns what saveEmailSettings stored

  it('round-trips enabled=true with all fields', () => {
    const original = { enabled: true, recipient: 'test@example.com', scheduleDay: 10, scheduleHour: 8, scheduleMinute: 30 };
    expect(simulateSettingsStorage(original)).toEqual(original);
  });

  it('round-trips enabled=false with empty recipient', () => {
    const original = { enabled: false, recipient: '', scheduleDay: 1, scheduleHour: 0, scheduleMinute: 0 };
    expect(simulateSettingsStorage(original)).toEqual(original);
  });

  it('round-trips boundary values', () => {
    const original = { enabled: true, recipient: 'boundary@test.com', scheduleDay: 28, scheduleHour: 23, scheduleMinute: 59 };
    expect(simulateSettingsStorage(original)).toEqual(original);
  });

  it('preserves recipient email exactly', () => {
    const original = { enabled: true, recipient: 'user+tag@sub.domain.com', scheduleDay: 5, scheduleHour: 9, scheduleMinute: 0 };
    const retrieved = simulateSettingsStorage(original);
    expect(retrieved.recipient).toBe(original.recipient);
  });
});

// ---------------------------------------------------------------------------
// 3. Scheduled send workflow wiring
// ---------------------------------------------------------------------------

describe('Scheduled send workflow wires all functions together', () => {
  // Validates: Requirements 4.1, 4.2, 4.3, 8.3

  it('skips send when automatic emails are disabled', () => {
    const settings = { enabled: false, recipient: 'admin@company.com', scheduleDay: 5, scheduleHour: 9, scheduleMinute: 0 };
    const result = simulateScheduledSend(settings, true, true);
    expect(result.skipped).toBe(true);
  });

  it('logs failure when PDF generation fails', () => {
    const settings = { enabled: true, recipient: 'admin@company.com', scheduleDay: 5, scheduleHour: 9, scheduleMinute: 0 };
    const result = simulateScheduledSend(settings, false, true);
    expect(result.success).toBe(false);
    expect(result.log.status).toBe('failed');
    expect(result.log.triggerType).toBe('scheduled');
    expect(result.log.errorMessage).toContain('PDF generation failed');
  });

  it('logs failure when email delivery fails', () => {
    const settings = { enabled: true, recipient: 'admin@company.com', scheduleDay: 5, scheduleHour: 9, scheduleMinute: 0 };
    const result = simulateScheduledSend(settings, true, false);
    expect(result.success).toBe(false);
    expect(result.log.status).toBe('failed');
    expect(result.log.triggerType).toBe('scheduled');
  });

  it('logs success when both PDF and email succeed', () => {
    const settings = { enabled: true, recipient: 'admin@company.com', scheduleDay: 5, scheduleHour: 9, scheduleMinute: 0 };
    const result = simulateScheduledSend(settings, true, true);
    expect(result.success).toBe(true);
    expect(result.log.status).toBe('success');
    expect(result.log.triggerType).toBe('scheduled');
    expect(result.log.recipient).toBe('admin@company.com');
  });

  it('log entry contains all required fields', () => {
    const settings = { enabled: true, recipient: 'admin@company.com', scheduleDay: 5, scheduleHour: 9, scheduleMinute: 0 };
    const result = simulateScheduledSend(settings, true, true);
    const log = result.log;
    expect(log).toHaveProperty('timestamp');
    expect(log).toHaveProperty('recipient');
    expect(log).toHaveProperty('monthYear');
    expect(log).toHaveProperty('status');
    expect(log).toHaveProperty('errorMessage');
    expect(log).toHaveProperty('triggerType');
  });

  it('monthYear in log uses YYYY-MM format', () => {
    const settings = { enabled: true, recipient: 'admin@company.com', scheduleDay: 5, scheduleHour: 9, scheduleMinute: 0 };
    const result = simulateScheduledSend(settings, true, true);
    expect(result.log.monthYear).toMatch(/^\d{4}-\d{2}$/);
  });
});

// ---------------------------------------------------------------------------
// 4. Manual send workflow wiring
// ---------------------------------------------------------------------------

describe('Manual send workflow wires all functions together', () => {
  // Validates: Requirements 6.1, 6.2, 6.3, 8.5

  it('fails with helpful message when no recipient configured', () => {
    const settings = { enabled: false, recipient: '', scheduleDay: 5, scheduleHour: 9, scheduleMinute: 0 };
    const result = simulateManualSend(settings, true, true);
    expect(result.success).toBe(false);
    expect(result.error).toContain('No recipient email configured');
  });

  it('fails with helpful message when recipient email is invalid', () => {
    const settings = { enabled: false, recipient: 'not-an-email', scheduleDay: 5, scheduleHour: 9, scheduleMinute: 0 };
    const result = simulateManualSend(settings, true, true);
    expect(result.success).toBe(false);
    expect(result.error).toContain('Invalid recipient email format');
  });

  it('logs failure when PDF generation fails', () => {
    const settings = { enabled: false, recipient: 'admin@company.com', scheduleDay: 5, scheduleHour: 9, scheduleMinute: 0 };
    const result = simulateManualSend(settings, false, true);
    expect(result.success).toBe(false);
    expect(result.log.status).toBe('failed');
    expect(result.log.triggerType).toBe('manual');
  });

  it('logs failure when email delivery fails', () => {
    const settings = { enabled: false, recipient: 'admin@company.com', scheduleDay: 5, scheduleHour: 9, scheduleMinute: 0 };
    const result = simulateManualSend(settings, true, false);
    expect(result.success).toBe(false);
    expect(result.log.status).toBe('failed');
    expect(result.log.triggerType).toBe('manual');
  });

  it('succeeds and logs correctly when all steps pass', () => {
    const settings = { enabled: false, recipient: 'admin@company.com', scheduleDay: 5, scheduleHour: 9, scheduleMinute: 0 };
    const result = simulateManualSend(settings, true, true);
    expect(result.success).toBe(true);
    expect(result.log.status).toBe('success');
    expect(result.log.triggerType).toBe('manual');
    expect(result.log.recipient).toBe('admin@company.com');
  });

  it('works regardless of automatic email enabled state', () => {
    const enabledSettings  = { enabled: true,  recipient: 'admin@company.com', scheduleDay: 5, scheduleHour: 9, scheduleMinute: 0 };
    const disabledSettings = { enabled: false, recipient: 'admin@company.com', scheduleDay: 5, scheduleHour: 9, scheduleMinute: 0 };

    const r1 = simulateManualSend(enabledSettings,  true, true);
    const r2 = simulateManualSend(disabledSettings, true, true);

    expect(r1.success).toBe(true);
    expect(r2.success).toBe(true);
  });

  it('returns recipient and monthYear for UI feedback', () => {
    const settings = { enabled: false, recipient: 'admin@company.com', scheduleDay: 5, scheduleHour: 9, scheduleMinute: 0 };
    const result = simulateManualSend(settings, true, true);
    expect(result.recipient).toBe('admin@company.com');
    expect(result.monthYear).toMatch(/^\d{4}-\d{2}$/);
  });
});

// ---------------------------------------------------------------------------
// 5. Previous-month calculation (handleScheduledEmailSend logic)
// ---------------------------------------------------------------------------

describe('Previous month calculation for scheduled send', () => {
  // Validates: Requirements 4.1 — trigger sends report for the previous month

  it('returns December of previous year when current month is January', () => {
    const jan2024 = new Date(2024, 0, 15); // January 15, 2024
    const result  = calculatePreviousMonth(jan2024);
    expect(result.month).toBe(12);
    expect(result.year).toBe(2023);
    expect(result.monthYear).toBe('2023-12');
  });

  it('returns previous month in same year for February through December', () => {
    const months = [
      { date: new Date(2024, 1, 15), expectedMonth: 1,  expectedYear: 2024, expectedStr: '2024-01' }, // Feb → Jan
      { date: new Date(2024, 2, 15), expectedMonth: 2,  expectedYear: 2024, expectedStr: '2024-02' }, // Mar → Feb
      { date: new Date(2024, 5, 15), expectedMonth: 5,  expectedYear: 2024, expectedStr: '2024-05' }, // Jun → May
      { date: new Date(2024, 11, 15), expectedMonth: 11, expectedYear: 2024, expectedStr: '2024-11' } // Dec → Nov
    ];

    months.forEach(({ date, expectedMonth, expectedYear, expectedStr }) => {
      const result = calculatePreviousMonth(date);
      expect(result.month).toBe(expectedMonth);
      expect(result.year).toBe(expectedYear);
      expect(result.monthYear).toBe(expectedStr);
    });
  });

  it('pads single-digit months with leading zero in monthYear string', () => {
    const march2024 = new Date(2024, 2, 15); // March → February
    const result    = calculatePreviousMonth(march2024);
    expect(result.monthYear).toBe('2024-02');
  });

  it('handles year boundary correctly (January → December previous year)', () => {
    const jan2025 = new Date(2025, 0, 1);
    const result  = calculatePreviousMonth(jan2025);
    expect(result.month).toBe(12);
    expect(result.year).toBe(2024);
    expect(result.monthYear).toBe('2024-12');
  });
});

// ---------------------------------------------------------------------------
// 6. Email composition wiring
// ---------------------------------------------------------------------------

describe('Email composition includes required elements', () => {
  // Validates: Requirements 4.5, 4.6, 8.3

  it('subject includes month name and year', () => {
    const email = composeEmail('admin@company.com', 3, 2024, 'Test Org');
    expect(email.subject).toContain('March');
    expect(email.subject).toContain('2024');
  });

  it('subject follows "Monthly Attendance Report - Month Year" format', () => {
    const email = composeEmail('admin@company.com', 6, 2023, 'Test Org');
    expect(email.subject).toBe('Monthly Attendance Report - June 2023');
  });

  it('body contains explanatory text about the attachment', () => {
    const email = composeEmail('admin@company.com', 1, 2024, 'Test Org');
    expect(email.body).toContain('attached');
    expect(email.body).toContain('attendance report');
  });

  it('body includes organization name', () => {
    const email = composeEmail('admin@company.com', 1, 2024, 'My Company');
    expect(email.body).toContain('My Company');
  });

  it('body includes month and year', () => {
    const email = composeEmail('admin@company.com', 8, 2024, 'Test Org');
    expect(email.body).toContain('August');
    expect(email.body).toContain('2024');
  });

  it('to field matches recipient', () => {
    const email = composeEmail('recipient@example.com', 1, 2024, 'Test Org');
    expect(email.to).toBe('recipient@example.com');
  });
});

// ---------------------------------------------------------------------------
// 7. Delivery log structure wiring
// ---------------------------------------------------------------------------

describe('Delivery log entries contain all required fields', () => {
  // Validates: Requirements 7.1, 7.2, 7.3, 7.6, 8.6

  it('success log entry has all required fields', () => {
    const log = createLogEntry('admin@company.com', '2024-03', 'success', 'scheduled', '');
    expect(log.timestamp).toBeTruthy();
    expect(log.recipient).toBe('admin@company.com');
    expect(log.monthYear).toBe('2024-03');
    expect(log.status).toBe('success');
    expect(log.errorMessage).toBe('');
    expect(log.triggerType).toBe('scheduled');
  });

  it('failure log entry includes error details', () => {
    const log = createLogEntry('admin@company.com', '2024-03', 'failed', 'manual', 'Network timeout');
    expect(log.status).toBe('failed');
    expect(log.errorMessage).toBe('Network timeout');
    expect(log.triggerType).toBe('manual');
  });

  it('timestamp is in ISO format', () => {
    const log = createLogEntry('admin@company.com', '2024-03', 'success', 'scheduled', '');
    expect(log.timestamp).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);
  });

  it('monthYear uses YYYY-MM format', () => {
    const log = createLogEntry('admin@company.com', '2024-03', 'success', 'scheduled', '');
    expect(log.monthYear).toMatch(/^\d{4}-\d{2}$/);
  });

  it('triggerType distinguishes scheduled from manual', () => {
    const scheduledLog = createLogEntry('admin@company.com', '2024-03', 'success', 'scheduled', '');
    const manualLog    = createLogEntry('admin@company.com', '2024-03', 'success', 'manual',    '');
    expect(scheduledLog.triggerType).toBe('scheduled');
    expect(manualLog.triggerType).toBe('manual');
  });
});

// ---------------------------------------------------------------------------
// 8. End-to-end workflow integration
// ---------------------------------------------------------------------------

describe('End-to-end email workflow integration', () => {
  // Validates: Requirements 4.1, 4.2, 4.3, 8.1–8.6

  it('complete configuration → trigger → scheduled send workflow', () => {
    // 1. Configure and persist settings
    const emailData = { enabled: true, recipient: 'admin@company.com', scheduleDay: 5, scheduleHour: 9, scheduleMinute: 0 };
    const stored    = simulateSettingsStorage(emailData);
    expect(stored.enabled).toBe(true);

    // 2. Create trigger from stored schedule
    const trigger = simulateTriggerLifecycle(stored.scheduleDay, stored.scheduleHour, stored.scheduleMinute);
    expect(trigger.success).toBe(true);

    // 3. Trigger fires → scheduled send
    const sendResult = simulateScheduledSend(stored, true, true);
    expect(sendResult.success).toBe(true);
    expect(sendResult.log.status).toBe('success');
    expect(sendResult.log.triggerType).toBe('scheduled');
  });

  it('complete configuration → manual send workflow', () => {
    // 1. Configure settings (disabled automatic, but manual should still work)
    const emailData = { enabled: false, recipient: 'admin@company.com', scheduleDay: 5, scheduleHour: 9, scheduleMinute: 0 };
    const stored    = simulateSettingsStorage(emailData);

    // 2. Manual send
    const sendResult = simulateManualSend(stored, true, true);
    expect(sendResult.success).toBe(true);
    expect(sendResult.log.triggerType).toBe('manual');
  });

  it('disabling feature stops scheduled sends but not manual sends', () => {
    const settings = { enabled: false, recipient: 'admin@company.com', scheduleDay: 5, scheduleHour: 9, scheduleMinute: 0 };

    const scheduledResult = simulateScheduledSend(settings, true, true);
    const manualResult    = simulateManualSend(settings, true, true);

    expect(scheduledResult.skipped).toBe(true);
    expect(manualResult.success).toBe(true);
  });

  it('error in one step does not corrupt subsequent log entries', () => {
    const settings = { enabled: true, recipient: 'admin@company.com', scheduleDay: 5, scheduleHour: 9, scheduleMinute: 0 };

    // First send fails
    const failResult = simulateScheduledSend(settings, false, true);
    expect(failResult.log.status).toBe('failed');

    // Second send succeeds — log should be independent
    const successResult = simulateScheduledSend(settings, true, true);
    expect(successResult.log.status).toBe('success');
  });

  it('schedule change updates trigger without breaking email delivery', () => {
    // Original schedule
    const original = simulateTriggerLifecycle(5, 9, 0);
    expect(original.success).toBe(true);

    // Updated schedule (simulates removeEmailScheduleTrigger + setupEmailScheduleTrigger)
    const updated = simulateTriggerLifecycle(15, 14, 30);
    expect(updated.success).toBe(true);
    expect(updated.triggerId).not.toBe(original.triggerId);

    // Email delivery still works with new schedule
    const settings = { enabled: true, recipient: 'admin@company.com', scheduleDay: 15, scheduleHour: 14, scheduleMinute: 30 };
    const sendResult = simulateScheduledSend(settings, true, true);
    expect(sendResult.success).toBe(true);
  });
});
